Repository insightsengineering/nestcolor, pull requests merged in 2022-07, with the labels that each got.

#12 add font_size argument to theme_nest
  R/theme_nest.R
  man/theme_nest.Rd
  tests/testthat/test-theme_nest.R
Labels: sme, core

#14 7 Add package authors/maintainers
  DESCRIPTION
Labels: sme

#13 updating installation instructions
  README.md
Labels: sme, core

#10 527 Add TMC as `nestcolor` downstream dependency
  NEWS.md
  staged_dependencies.yaml
Labels: sme

#21 Accessible color palette
  .gitignore
  R/color_palette.R
Labels: enhancement, sme

#23 294 Add Getting Started vignette, update README
  NEWS.md
  R/color_palette.R
  README.md
  inst/WORDLIST
  man/color_palette.Rd
  tests/testthat/test-color_palette.R
  vignettes/nestcolor.Rmd
Labels: sme
